# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
  name: nginx2
  namespace: kyverno-test
spec:
  containers:
    - name: nginx2
      image: nginx
      resources: {}
